## Numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Array(ndarray)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex) #dtypeでデータ型を指定できる

In [12]:
type(matrix[0][0])

numpy.complex128

In [13]:
type(1)

int

In [14]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [20]:
ndarray = np.array([1,2,3], dtype=np.uint8)# unsigned  +- integer 8bit

unsigned：0か正の値　8bit =2の8乗=256　
→0〜255の値（一般的な画像データを扱う場合にこの形式を使う)

dtype=float32：機械学習に使うデータを保存するときによく使う  
dtype=float64：実際のモデル学習には64bitで学習することが多い

In [23]:
ndarray.astype(np.float64) #.astypeで元のndarrayのdtypeを変更

array([1., 2., 3.])

## ndarrayの演算

In [25]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
a = [1,2,3]
b = [1,2,3]

In [34]:
a + b

[1, 2, 3, 1, 2, 3]

In [35]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

普通のリストでは要素ごとの演算ができない

In [42]:
array1 = np.array([[1,2,3]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3 = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [37]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [44]:
array2 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Broadcasting:要素の数が一致しなくても、自動で補ってくれる

In [46]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
a = [1,2,3]
a + 3

TypeError: can only concatenate list (not "int") to list

## Shape

In [50]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [53]:
array1 = np.array([1,2])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

In [55]:
ndarray = np.array([[1,2],[3,4],[5,6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
ndarray.shape #↓3行2列であることが確認できる

(3, 2)

In [61]:
ndarray.reshape(2,3) #2行3列へ変更

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
ndarray.reshape(1,3) #↓サイズが合わないとエラー(3×2=6の元のarrayに対して1×3=3にreshapeはできない)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [75]:
ndarray1 = np.array([1,2,3]) #1次元のベクトル
ndarray2 = np.array([[1,2,3]]) #2次元の行列

In [68]:
ndarray1

array([1, 2, 3])

In [72]:
print(ndarray1.shape) #ベクトル

(3,)


In [71]:
ndarray2

array([[1, 2, 3]])

In [73]:
print(ndarray2.shape) #1行3列の行列

(1, 3)


In [87]:
expand_ndarray = np.expand_dims(ndarray1,axis=-1) #次元を増やす axisはindex axis=-1にすると最後のrankを追加

In [88]:
expand_ndarray.shape

(3, 1)

In [96]:
np.squeeze(expand_ndarray) #次元を減らす　→１の部分がなくなる

array([1, 2, 3])

In [97]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
ndarray.shape

(3, 3)

In [100]:
ndarray.flatten() #arrayを1次元にする

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [101]:
ndarray = np.array([1,2,3,4])

In [102]:
ndarray

array([1, 2, 3, 4])

In [104]:
ndarray[-1]

4

In [120]:
ndarray = np.array([[1,2],[3,4],[5,6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
ndarray[0][1]

2

In [125]:
ndarray[0,1] #左のようにまとめて記述するのが一般的(0行目の1列目)

2

In [126]:
ndarray = np.array([1,2,3,4])
ndarray

array([1, 2, 3, 4])

In [127]:
ndarray[1:3]

array([2, 3])

In [128]:
ndarray[:3]

array([1, 2, 3])

In [130]:
ndarray[1:]

array([2, 3, 4])

In [132]:
ndarray[-2:]

array([3, 4])

In [133]:
ndarray[:-2]

array([1, 2])

In [147]:
ndarray[:] #全ての意味

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [136]:
ndarray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [137]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [140]:
ndarray[:3] #0行目から2行目

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [142]:
ndarray[:3,2:] #0行目から2行目　かつ　　2列目以上

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [146]:
ndarray[:3][2:] #0行目から2行目　かつ　2行目以上　→上のスライシングとは意味が異なるので注意

array([[ 9, 10, 11, 12]])

In [149]:
ndarray[:,2:] #全ての行　かつ　2列目以上

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

## np.arange(),np.linspace(),np.logspace() 　配列を作成する関数

In [154]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
np.arange(3,15,2) #3以上15未満2ステップの配列を作る

array([ 3,  5,  7,  9, 11, 13])

In [158]:
np.arange(10,1,-1) #10〜1まで1ステップの配列を作る→ステップを負の数にすれば降順も可能

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [159]:
list(range(3,15,2)) #range関数と同じような使い方

[3, 5, 7, 9, 11, 13]

In [176]:
np.linspace(0,10,5) #0以上10以下の数を5等分で区切った値を出力

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [178]:
np.logspace(0,3,10) #10の0乗〜10の3乗までの数で、10の乗数(0<=x<=3)を10等分に区切った値を出力

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [168]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [170]:
10**0.3333

2.1542693374042363

In [175]:
np.linspace(0,10,5,endpoint=False) #linspaceとlogspaceは、endpoint=Falseという引数により、stopの数字以下ではなく、未満で出力可能

array([0., 2., 4., 6., 8.])

## np.zeros(shape) 　要素が全て0のndarrayを作成

In [5]:
shape = (3,4) #numpyのshapeはtuple形式で操作
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros(3) #引数にtupleではなくintを入れると、一列のarrayができる

array([0., 0., 0.])

## np.ones(shape) 　要素が全て1のndarrayを作成

In [7]:
shape = (5,4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((5,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## np.eye(shape) 

N×Nの単位行列を作成 (単位行列とは対角成分が全て1の正方行列のこと)

In [13]:
# I　→Identify matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3,4) #行列指定により、正方行列以外も作成可能

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.randomを使って乱数作成

### np.random.rand()  単純に乱数生成→毎回違う値が生成される

In [32]:
## 擬似乱数　pseudo random→データサイエンスでは擬似乱数で問題ない
np.random.rand()

0.14301782393398466

In [29]:
np.random.rand(3,4) #引数を入れるとndarrayを返す

array([[0.31849936, 0.48288066, 0.68129849, 0.69239367],
       [0.07880332, 0.67277792, 0.3769621 , 0.6556934 ],
       [0.63615041, 0.49627448, 0.10165235, 0.9996768 ]])

### np.random.seed   seedを指定すると、毎回同じ乱数を生成してくれる

In [43]:
np.random.seed(1) #自分の作ったコードやモデルを他人が再現できるようにするために、乱数生成にはなるべくseedを使う
np.random.rand()

0.417022004702574

In [44]:
np.random.rand() #セルが変わるとseedを指定しても乱数が変わる→seedは同じセル内でしか影響されない

0.7203244934421581

### np.random.randn()  標準正規分布(平均が0、分散が1の正規分布)からランダムに値を取得する

In [65]:
np.random.randn(3,4) #データサイエンスでは標準正規分布がよく使われる

array([[-1.94258918, -2.50644065, -2.11416392, -0.41163916],
       [ 1.27852808, -0.44222928,  0.32352735, -0.10999149],
       [ 0.00854895, -0.16819884, -0.17418034,  0.4611641 ]])

In [64]:
np.random.normal(0,1) #任意の平均と標準偏差の正規分布から擬似乱数を生成

-2.037201225680795

### np.random.randint(low,high = None,size = None)  　low以上high未満のランダムな整数でsizeのndarrayを生成

In [66]:
np.random.randint(10,100,(2,3))

array([[37, 48, 94],
       [43, 11, 41]])

In [67]:
np.random.randint(10) #high=Noneの場合は0以上low未満

5

### np.random.choice() 　 指定したndarray(list)からランダムな値を取得する

In [72]:
a = [1,2,3]
np.random.choice(a)

3

In [73]:
index_pool = np.arange(0,10,2)
index_pool

array([0, 2, 4, 6, 8])

In [77]:
idx = np.random.choice(index_pool)

In [ ]:
ndarray[idx]

##  統計量を求める

In [2]:
std_norm = np.random.randn(5,5)
std_norm

array([[-0.68054269,  1.81421132,  0.4057973 ,  0.94748522,  0.04528561],
       [-0.28327305, -0.86353496,  1.3176292 ,  2.37085125, -0.10042583],
       [ 2.02310298,  0.79069399, -0.34803175,  0.35568462, -0.42125596],
       [-1.35038784,  0.92734489, -0.48991208,  0.24067428, -0.15175072],
       [-0.07010585,  0.65071145, -1.48126625,  1.02016838,  0.31633025]])

In [3]:
#最大値
std_norm.max()

2.370851246421891

In [4]:
np.max(std_norm)

2.370851246421891

In [5]:
#最小値
std_norm.min()

-1.4812662457341852

In [6]:
np.min(std_norm)

-1.4812662457341852

In [11]:
#最大値のindexを取得→1行にした時のindex
std_norm.argmax()

8

In [7]:
std_norm.max()

2.370851246421891

In [10]:
std_norm.flatten()[8]

2.370851246421891

In [12]:
#最小値のindexを取得→1行にした時のindex
std_norm.argmin()

22

In [14]:
std_norm.min()

-1.4812662457341852

In [13]:
std_norm.flatten()[22]

-1.4812662457341852

In [15]:
#平均値を取得
std_norm.mean()

0.2794193508138789

In [16]:
#中央値を取得  max,min,meanと異なり、ndarrayから直接取得できないことに注意
np.median(std_norm)

0.24067427966130425

In [23]:
#中央値 vs 平均値
#time.time()で現時点での時間を測定
import time
a = np.random.randn(1000,1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))
#中央値は並び替えのせいで平均値より処理に時間がかかる

median took 0.014407157897949219 sec
mean took 0.0006320476531982422 sec


In [26]:
#標準偏差(分散の平方根)を取得
np.std(std_norm)

0.9585654575756741

In [33]:
#max,min,meanなどにaxisを指定することで、行毎、列毎の統計量を測定可能→axis=0は列毎、axis=1は行毎
std_norm.max(axis=0)

array([2.02310298, 1.81421132, 1.3176292 , 2.37085125, 0.31633025])

## 数学で使う便利関数

In [34]:
#　平方根 square root
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
# log (logarithm)
np.log(1)

0.0

In [40]:
np.log2(8)

3.0

In [50]:
x= np.linspace(1,10,10) 
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
np.log(x)#底はデフォルトでネイピア数(2.718..)→最強の増え方をする数字

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [44]:
# 指数関数 Exponential function #デフォルトはネイピア数
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [60]:
np.exp2(10)

1024.0

In [45]:
#　ネイピア数：最強の増え方をする数字
np.e

2.718281828459045

In [63]:
#合計 (sumation)
np.sum([1,2,3])

6

In [64]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.sum(array)

55

In [67]:
ndarray = array.reshape(2,5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
np.sum(ndarray,axis=0)

array([ 7,  9, 11, 13, 15])

In [71]:
#絶対値 absolute value
array = np.arange(-10,0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [72]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.isnan()

In [73]:
# NaN : Not a Number

In [74]:
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [75]:
np.nan

nan

In [76]:
type(np.nan)

float

In [77]:
a = None
a is None

True

In [78]:
np.isnan(np.log(-100)) #nanチェックに利用

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## その他便利関数

## np.clip()

In [3]:
import numpy as np
array= np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.clip(array,3,7) #最小値,最大値を設定し、最小値以下の数値は最小値に、最大値以上の数字は最大値に変更

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [7]:
1e-4

0.0001

## numpy arrayのcondition

In [9]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np.where 条件指定

In [16]:
np.where(array > 3, 1, 0) #条件がTrueの要素は1に、Falseの要素は0に置き換わる

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [19]:
np.where(array > 3) #条件のみ指定すると、その条件に一致するindexが返ってくる

(array([4, 5, 6, 7, 8, 9]),)

In [26]:
result, = np.where(array > 3) #,をつけて代入することで、unpackできる

In [27]:
result

array([4, 5, 6, 7, 8, 9])

In [22]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
array[array>3] #ndarrayをfilterする時は、whereよりこちらが一般的

array([4, 5, 6, 7, 8, 9])

In [46]:
ndarray = array.reshape(2,5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
ndarray[ndarray>3] #多次元配列でfilterした場合、結果は1次元で返ってくる

array([4, 5, 6, 7, 8, 9])

In [56]:
ndarray > 3 #True or Falseは多次元配列の形を保ったままになる

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
(ndarray > 3).all() #全ての要素が条件を満たすかどうかを判定

False

In [59]:
(ndarray > 3).any() # 1つでも条件を満たすかどうか判定

True

In [60]:
(ndarray > 3).all(axis=0) #列毎に判定

array([False, False, False, False,  True])

## np.unique

In [47]:
array = np.array([1,1,2,3,4,2,3,4,5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [48]:
np.unique(array) #重複を除いた結果を出力

array([1, 2, 3, 4, 5])

In [50]:
np.unique(array,return_counts = True) #return_counts=Trueで、各要素のカウントを返す

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

## np.bincount()

In [55]:
np.bincount(array) # 0,1,2,3...の各カウント数を返す→unique関数だと、arrayに含まれる要素の数しかカウントできないが、bincountなら0からカウントできる

array([0, 2, 2, 2, 2, 1])

## np.concatenate()とnp.stack()

In [61]:
ndarray_even = np.arange(0,18,2).reshape(3,3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [63]:
ndarray_odd = np.arange(1,19,2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [69]:
np.concatenate([ndarray_even,ndarray_odd],axis=1) #arrayを連結（axisのデフォルトは0）

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [103]:
np.stack([ndarray_even,ndarray_odd],axis =-1) #新たなaxisを作成し、データを連結(axisのデフォルトは0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [79]:
stacked_array = _

In [84]:
stacked_array.shape #axisを指定した場所が「2」になる(axisは座標のindexのようなもの)→下の場合は奥行き：3、高さ：３、横：２となる

(3, 3, 2)

## np.transpose()  ndarray.T (転置：axisの入れ替え）

In [85]:
ndarray = np.random.randn(3,4)
ndarray

array([[-0.52347675, -2.02769186,  0.53409659,  0.90064742],
       [ 1.46660008,  0.00637685,  0.96607734,  0.6655446 ],
       [-1.25135651,  0.39097957, -1.73969435,  0.57850149]])

In [86]:
ndarray.shape

(3, 4)

In [96]:
np.transpose(ndarray) #行と列の入れ替え

array([[-0.52347675,  1.46660008, -1.25135651],
       [-2.02769186,  0.00637685,  0.39097957],
       [ 0.53409659,  0.96607734, -1.73969435],
       [ 0.90064742,  0.6655446 ,  0.57850149]])

In [97]:
transpose_ndarray = _ 

In [98]:
transpose_ndarray.shape

(4, 3)

In [99]:
ndarray.T #行と列の入れ替え(np.transposeと同じ)

array([[-0.52347675,  1.46660008, -1.25135651],
       [-2.02769186,  0.00637685,  0.39097957],
       [ 0.53409659,  0.96607734, -1.73969435],
       [ 0.90064742,  0.6655446 ,  0.57850149]])

In [100]:
ndarray = np.random.randn(3,4,5)
ndarray

array([[[ 0.5294766 , -0.48567759, -0.53620717,  0.011815  ,
         -0.4965709 ],
        [ 0.27770131,  0.35234971,  2.27504998, -1.02458658,
          0.82373911],
        [ 0.8833848 ,  0.44975195, -1.30192587,  0.5229841 ,
          0.45905214],
        [-2.10215341,  0.65819204, -0.34800725, -1.56779921,
          1.81501038]],

       [[ 1.01639275,  1.4110589 ,  0.70977589,  0.87562109,
          2.18035143],
        [-1.71875352,  0.4988732 ,  0.42775535, -0.16274013,
         -0.08909955],
        [ 0.68451878,  2.4652998 ,  0.35288883,  2.18218612,
         -0.88465026],
        [-0.72679504, -2.36032518, -0.43568194, -0.49922371,
         -1.8069628 ]],

       [[-0.50060509,  1.80368674,  1.00529926,  0.9762803 ,
          0.18806928],
        [-0.23360362,  0.21842143,  1.16756321,  0.34302734,
         -1.25750997],
        [ 1.47158911,  0.94413938, -0.77880291,  0.90279899,
          0.19384288],
        [-0.21625959, -1.10542681, -0.25963677,  1.19747362,
         -1

In [102]:
ndarray.T.shape

(5, 4, 3)

## np.save('path',array)とnp.load('path')

In [105]:
ndarray = np.random.randn(3,4,5)
ndarray.shape

(3, 4, 5)

In [114]:
np.save('sample_ndarray.npy',ndarray) #.npyは自動補完される

In [111]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [118]:
dictionary = {
    'id':123456,
    'image':ndarray
}

In [119]:
np.save('sample_dict',dictionary) #dictionaryも.npyとして保存可能

In [123]:
loaded_dict = np.load('sample_dict.npy',allow_pickle=True) #allow_pickle=Trueでdictionaryをload可能  

In [124]:
loaded_dict

array({'id': 123456, 'image': array([[[ 0.71789807,  0.06812435, -1.49735765,  0.30506946,
          1.12617466],
        [-1.52680963,  0.83796902, -0.37815518, -0.02487018,
          0.8454391 ],
        [ 0.28041249, -0.62135727,  0.95769141,  0.69066921,
         -0.39765989],
        [ 0.42045684,  1.39569725, -2.61965608,  1.61582421,
         -0.6715863 ]],

       [[ 2.18397649,  0.22958025, -0.90769504, -0.98469461,
          0.33592917],
        [ 0.87591086,  0.47099694,  1.9303492 , -1.51956002,
         -0.51620602],
        [ 0.50290405,  1.15590274,  0.70621668, -2.48820987,
          1.60601667],
        [ 1.54271455, -0.66318158,  0.5284117 , -0.64050856,
         -0.08177276]],

       [[-0.99052452,  0.18712875, -0.32823492, -0.58899432,
         -0.12912597],
        [-0.2066792 , -0.40838168,  0.1462436 ,  1.77205136,
         -0.22341706],
        [-1.13918322, -0.09166885,  1.50153542, -1.39340669,
         -0.52504337],
        [-0.64564659,  0.86748707, -1.0110

In [130]:
loaded_dict[()] #[()]で中のdictinaryを取り出す

{'id': 123456,
 'image': array([[[ 0.71789807,  0.06812435, -1.49735765,  0.30506946,
           1.12617466],
         [-1.52680963,  0.83796902, -0.37815518, -0.02487018,
           0.8454391 ],
         [ 0.28041249, -0.62135727,  0.95769141,  0.69066921,
          -0.39765989],
         [ 0.42045684,  1.39569725, -2.61965608,  1.61582421,
          -0.6715863 ]],
 
        [[ 2.18397649,  0.22958025, -0.90769504, -0.98469461,
           0.33592917],
         [ 0.87591086,  0.47099694,  1.9303492 , -1.51956002,
          -0.51620602],
         [ 0.50290405,  1.15590274,  0.70621668, -2.48820987,
           1.60601667],
         [ 1.54271455, -0.66318158,  0.5284117 , -0.64050856,
          -0.08177276]],
 
        [[-0.99052452,  0.18712875, -0.32823492, -0.58899432,
          -0.12912597],
         [-0.2066792 , -0.40838168,  0.1462436 ,  1.77205136,
          -0.22341706],
         [-1.13918322, -0.09166885,  1.50153542, -1.39340669,
          -0.52504337],
         [-0.64564659,  